#!/bin/bash
cd $(dirname $(dirname ${BASH_SOURCE[0]}))

TARGET="$(realpath shell-init)"
CONTENT=$(cat << EOF

# Custom aliases and definitions
if [ -f ~/.shell_profile ]; then
    . ~/.shell_profile
fi
EOF
)

# Symlink ~/.shell_profile to profile
echo "Symlinking ~/.shell_profile to $TARGET"
ln -sri "$TARGET" ~/.shell_profile

# Source ~/.shell_profile in ~/.bashrc and ~/.zshrc
for RCFILE in ~/.bashrc ~/.zshrc; do
    if [[ -f $RCFILE ]]; then
        if ! grep -q ". ~/.shell_profile" $RCFILE; then
            echo "Adding ~/.shell_profile to $RCFILE"
            echo "$CONTENT" >> $RCFILE
        else
            echo "Already sourcing ~/.shell_profile in $RCFILE"
        fi
    fi
done
