# Global settings
set -g mouse on
set -g default-terminal tmux-256color
set -g window-size largest
set -g history-limit 5000
set -g default-command "${SHELL}"
set -g mode-keys vi
set -g display-panes-time 2000

# Keybindings
bind '"' split-window -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"
bind 'h' setw synchronize-panes
bind 'X' if-shell -F '#{pane_input_off}' 'select-pane -e' 'select-pane -d'
bind 'S' swap-pane

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'omerxx/tmux-floax'
set -g @floax-change-path 'false'
set -g @floax-bind 'j'
set -g @floax-bind-menu 'J'

# Themes
set -g @plugin 'nordtheme/tmux'
#set -g @plugin 'catppuccin/tmux'

# tmux plugin manager
run '~/.tmux/plugins/tpm/tpm'
