#!/bin/bash
cd $(dirname $(dirname ${BASH_SOURCE[0]}))

setup_dotfiles_group() {
    if [[ $# -ne 1 ]]; then
        echo "The dotfiles group name to install must be provided"
        return 1
    fi

    if ! cd "dotfiles/$1"; then
        echo "$1: this dotfiles group doesn't exist"
        return 2
    fi

    # Making symlinks to files in the dotfiles group
    for file in $(find -type f -not -path "*/.git/*"); do
        target=$(realpath --relative-to . "$file")
        mkdir -p "$(dirname "$HOME/$target")"
        if [[ -L $HOME/$target ]]; then
            echo "$HOME/$target is already a symlink. Overwriting..."
            rm "$HOME/$target"
        fi
        ln -sri "$target" "$HOME/$target"
    done
    
    cd "$OLDPWD"
}

if [[ $# -eq 0 ]]; then
    for group in dotfiles/*; do
        if [[ -d $group ]]; then
            echo "Setting up dotfiles group $(basename "$group")..."
            setup_dotfiles_group "$(basename "$group")"
        fi
    done
else
    while (($#)); do
        if [[ -d dotfiles/$1 ]]; then
            echo "Setting up dotfiles group $1..."
            setup_dotfiles_group "$1"
        else
            echo "$1: this dotfiles group doesn't exist"
        fi 
        shift
    done
fi